nodeLinker: hoisted

packages:
  - src/node/os/get-running-process-exit-code

allowBuilds:
  electron-winstaller: true
  esbuild: true
  registry-js: true

overrides:
  esbuild: '$esbuild'
  node-gyp: '$node-gyp'
  vite: '$vite'
  vitest: '$vitest'
  # To remove when https://github.com/electron/electron/issues/51619 is resolved
  yauzl: '3.3.1'
  '@voidzero-dev/vite-plus-core': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1703'
  '@voidzero-dev/vite-plus-test': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1703'
  '@voidzero-dev/vite-plus-prompts': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-prompts@1703'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

blockExoticSubdeps: false

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
