nodeLinker: hoisted

packages:
  - src/node/os/get-running-process-exit-code

allowBuilds:
  electron-winstaller: true
  esbuild: true
  registry-js: true
  '@akiver/cs-demo-analyzer': true

overrides:
  esbuild: '$esbuild'
  node-gyp: '$node-gyp'
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vitest: '4.1.9'
  # To remove when https://github.com/electron/electron/issues/51619 is resolved
  yauzl: '3.3.1'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@akiver/cs-demo-analyzer'
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false
