nodeLinker: hoisted

packages:
  - src/node/os/get-running-process-exit-code

allowBuilds:
  electron-winstaller: true
  esbuild: true
  registry-js: true

blockExoticSubdeps: false
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
  - vitest
  - '@vitest/*'

overrides:
  '@voidzero-dev/vite-plus-core': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@5577b0154f33d1480a3c96347e94fa5d2094de2e'
  '@voidzero-dev/vite-plus-prompts': 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-prompts@5577b0154f33d1480a3c96347e94fa5d2094de2e'
  esbuild: '$esbuild'
  node-gyp: '$node-gyp'
  vite: '$vite'
  # To remove when https://github.com/electron/electron/issues/51619 is resolved
  yauzl: '3.3.1'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
